"""Alle Event-Typen für das DFlowP Framework."""

EVENT_STARTED = "EVENT_STARTED"
EVENT_COMPLETED = "EVENT_COMPLETED"
EVENT_FAILED = "EVENT_FAILED"
# Noch nicht implementiert:
# EVENT_PROGRESS = "EVENT_PROGRESS"
# EVENT_LOG = "EVENT_LOG"

EVENT_TYPES = (
    EVENT_STARTED,
    EVENT_COMPLETED,
    EVENT_FAILED,
)
