#!/usr/bin/env python3
"""Erzeugt ./Dockerfile aus modules.json (Multi-Stage: wheels + Services)."""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from ci_lib import all_paths, load_modules, repo_root


def sh_cmd(cmd: list[str]) -> str:
    return json.dumps(cmd)


def main() -> int:
    root = repo_root()
    modules = load_modules()
    pkgs, svcs = all_paths(modules)
    py_img = modules.get("docker", {}).get("python_image", "python:3.11-slim-bookworm")

    lines: list[str] = [
        "# Generated by scripts/ci_generate_dockerfile.py",
        f"FROM {py_img} AS wheel-builder",
        "ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1",
        "WORKDIR /build",
        "RUN python -m ensurepip --upgrade \\",
        "    && python -m pip install --upgrade pip setuptools wheel build",
    ]

    whl_names: list[str] = []
    for p in pkgs:
        slug = Path(p).name.replace("-", "_")
        whl_names.append(slug)
        lines.append(f"COPY {p} /src/{slug}")
        lines.append(
            f"RUN python -m pip install -r /src/{slug}/requirements.txt \\"
        )
        lines.append(
            f"    && cd /src/{slug} && python -m build --wheel -o /out \\"
        )
        lines.append(
            f"    && cp /out/*.whl /build/{slug}.whl"
        )

    for svc in svcs:
        target = modules["docker"]["stage_targets"][svc]
        cmd = modules["docker"]["cmd"][svc]
        slug_svc = Path(svc).name.replace("-", "_")
        lines.append("")
        lines.append(f"FROM {py_img} AS {target}")
        lines.append("WORKDIR /app")
        lines.append(f"COPY {svc} /app")
        for slug in whl_names:
            lines.append(f"COPY --from=wheel-builder /build/{slug}.whl /tmp/{slug}.whl")
        install_wheels = " && ".join(
            f"python -m pip install --no-cache-dir /tmp/{s}.whl" for s in whl_names
        )
        req = (root / svc / "requirements.txt").exists()
        lines.append(
            "RUN python -m ensurepip --upgrade && python -m pip install --upgrade pip \\"
        )
        lines.append(f"    && {install_wheels}" + (f" \\\n    && python -m pip install --no-cache-dir -r /app/requirements.txt" if req else ""))
        lines.append(f"CMD {sh_cmd(cmd)}")

    out = root / "Dockerfile"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
