#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="${1:-$(dirname "$0")/../.env.remote-hmr.example}"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Env file not found: $ENV_FILE" >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

: "${DFLOWP_REMOTE_HMR_SSH_TARGET:?missing DFLOWP_REMOTE_HMR_SSH_TARGET}"
: "${DFLOWP_REMOTE_HMR_VITE_PORT:?missing DFLOWP_REMOTE_HMR_VITE_PORT}"
: "${DFLOWP_REMOTE_HMR_SUPERVISOR_PORT:?missing DFLOWP_REMOTE_HMR_SUPERVISOR_PORT}"
: "${DFLOWP_REMOTE_HMR_LOCAL_VITE_PORT:?missing DFLOWP_REMOTE_HMR_LOCAL_VITE_PORT}"
: "${DFLOWP_REMOTE_HMR_LOCAL_SUPERVISOR_PORT:?missing DFLOWP_REMOTE_HMR_LOCAL_SUPERVISOR_PORT}"

echo "Opening SSH tunnel to ${DFLOWP_REMOTE_HMR_SSH_TARGET}"
echo "Vite:       127.0.0.1:${DFLOWP_REMOTE_HMR_LOCAL_VITE_PORT} -> 127.0.0.1:${DFLOWP_REMOTE_HMR_VITE_PORT}"
echo "Supervisor: 127.0.0.1:${DFLOWP_REMOTE_HMR_LOCAL_SUPERVISOR_PORT} -> 127.0.0.1:${DFLOWP_REMOTE_HMR_SUPERVISOR_PORT}"
echo "Press Ctrl+C to close the tunnel."

ssh -N \
  -L "${DFLOWP_REMOTE_HMR_LOCAL_VITE_PORT}:127.0.0.1:${DFLOWP_REMOTE_HMR_VITE_PORT}" \
  -L "${DFLOWP_REMOTE_HMR_LOCAL_SUPERVISOR_PORT}:127.0.0.1:${DFLOWP_REMOTE_HMR_SUPERVISOR_PORT}" \
  "${DFLOWP_REMOTE_HMR_SSH_TARGET}"
